### ISSUE TITLE
Problem Installing Grafana

### ISSUE THREAD

**Issue by DanWinchester** [grafana/tutorials#106] opened 2021-02-21 15:25 UTC
pi@raspberrypi:~ $ wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
OK
pi@raspberrypi:~ $ echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
deb https://packages.grafana.com/oss/deb stable main
pi@raspberrypi:~ $ sudo apt-get update
E: Type 'gpg' is not known on line 1 in source list /etc/apt/sources.list.d/grafana.list
E: The list of sources could not be read.

**Comment by matthewhelmke** [comment] 2021-06-29 18:07
Closing. Unable to reproduce.

**Closed by matthewhelmke** 2021-06-29 18:07 UTC
