### ISSUE TITLE
Not able to add Notification Channel

### ISSUE THREAD

**Issue by consal** [grafana/tutorials#116] opened 2021-04-30 14:35 UTC
I've been following the fundamentals tutorial. I'm not able to test a newly added notification channel due to the following error in the logs:
```
t=2021-04-30T14:30:35+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=1 orgId=1 uname=admin error="Post \"https://hookb.in/b9qDpGeQJQC3DDogXrXN\": x509: certificate signed by unknown authority" remote_addr=172.22.0.1
```
I tried `hookb.in` and `requestbin.com` - I'm getting the same error on both.

**Comment by matthewhelmke** [comment] 2021-06-29 18:16
Apologies. It's been a long time since you asked your question. You are likely to have more luck getting a response (if you still have need) in either the Grafana [slack](https://grafana.slack.com/) or the [forums](https://community.grafana.com/).

Closing as I have been unable to reproduce.

**Closed by matthewhelmke** 2021-06-29 18:16 UTC
