### ISSUE TITLE
Add note about plugin signature verification

### ISSUE THREAD

**Issue by marefr** [grafana/tutorials#65] opened 2020-06-05 07:57 UTC
Backend plugins requires to be signed for Grafana to load/start them. Need to add information about this, especially for backend plugin data source tutorial.

https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/#backend-plugins

**Comment by marcusolsson** [comment] 2020-06-05 08:10
Duplicate of #58

**Closed by marcusolsson** 2020-06-05 08:10 UTC
Labels: enhancement
