### ISSUE TITLE
Backend Tutorial - the plugin is not in the list.

### ISSUE THREAD

**Issue by jramineni** [grafana/tutorials#75] opened 2020-08-15 22:36 UTC
Following the tutorial to build back end using grafana docker.  At the end of "Create a new plugin"  after building both front end and backend, when the docker image is launched with 
docker run -d -p 3000:3000 -v "$(pwd)"/grafana-plugins:/var/lib/grafana/plugins --name=grafana grafana/grafana:7.0.0

The new plugin is not listed in UI and nor any error displayed.

When src/plugin.json is changed to set  "backend": false,  and docker is reloaded, the plugin displays 

Is the docker unable to load the backend binary? 

Did exec into docker, there are files in /var/log/grafana

docker logs shows this error
t=2020-08-15T22:28:06+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"test-mybktest\" is unsigned" pluginPath=/var/lib/grafana/plugins/my-plugin/dist

**Comment by marcusolsson** [comment] 2020-08-17 07:57
By default, Grafana only loads _signed_ backend plugins. To load unsigned backend plugins you need to allow them in the config: 

For more information, refer to [Allow unsigned plugins](https://grafana.com/docs/grafana/latest/plugins/plugin-signature-verification/#allow-unsigned-plugins).

Duplicate of #58

**Closed by marcusolsson** 2020-08-17 07:57 UTC
