### ISSUE TITLE
doesn't work on ARMv6 Raspberries

### ISSUE THREAD

**Issue by vidmo91** [grafana/tutorials#104] opened 2021-02-15 16:39 UTC
You should at least inform users about compatibility in this tutorial.

**Comment by marcusolsson** [comment] 2021-02-15 16:58
We definitely should! Though I'd also like to figure out if we can get it to work on ARMv6 as well

**Comment by vidmo91** [comment] 2021-02-15 20:14
It works fine. I downloaded ARMv6 from link below and followed other instructions from this tutorial.
https://grafana.com/grafana/download?platform=arm

**Comment by matthewhelmke** [comment] 2021-06-29 18:03
Closing. Unable to reproduce.

**Closed by matthewhelmke** 2021-06-29 18:03 UTC
Labels: documentation
