### ISSUE TITLE
API endpoint

### ISSUE THREAD

**Issue by SpAndrea117** [grafana/tutorials#92] opened 2020-10-08 08:41 UTC
How can I identify the API endpoint necessary for the url line in the last step of tutorial build a data source plugin?

**Comment by marcusolsson** [comment] 2020-10-08 14:17
This looks like a duplicate of https://github.com/grafana/tutorials/issues/92, where I've already answered.

**Closed by marcusolsson** 2020-10-08 14:17 UTC

**Comment by SpAndrea117** [comment] 2020-10-08 14:26
If I try to open the link to #92 i obtain only my question without any response to it. Could I ask more details about where I can found the answer? Thanks for your help.

**Comment by marcusolsson** [comment] 2020-10-08 14:44
Sorry, I meant  https://github.com/grafana/tutorials/issues/91.
