### ISSUE TITLE
tutorials/grafana-fundamentals/Set up the sample application do not work on RPI2

### ISSUE THREAD

**Issue by angelosne** [grafana/tutorials#102] opened 2021-01-23 13:20 UTC
After going through all steps in the [tutorial](https://grafana.com/tutorials/grafana-fundamentals/?utm_source=grafana_gettingstarted#2) the docker-compose ps gives me:
```
pi@docker:~/tutorial-environment $ docker-compose ps
              Name                             Command               State            Ports
----------------------------------------------------------------------------------------------------
tutorial-environment_app_1          /bin/sh -c /app http://db  ...   Exit 2
tutorial-environment_db_1           /db                              Exit 1
tutorial-environment_grafana_1      /run.sh                          Up       0.0.0.0:3000->3000/tcp
tutorial-environment_loki_1         /usr/bin/loki -config.file ...   Up       0.0.0.0:3100->3100/tcp
tutorial-environment_prometheus_1   /bin/prometheus --config.f ...   Up       0.0.0.0:9090->9090/tcp
tutorial-environment_promtail_1     /usr/bin/promtail -config. ...   Up
```

The first two state is Exit.
When I try to open the rpiAddress:8081 nothing comes up. 
I use ssh and it is a freshly installed Raspbian fully updated. I just created for this tutorial.

**Comment by dakotawild** [comment] 2021-03-20 12:05
Same problem here. Any update pls ?

**Comment by LoLo2207** [comment] 2021-03-31 17:02
https://github.com/grafana/tutorial-environment/issues/5

**Comment by matthewhelmke** [comment] 2021-06-29 18:59
As far as I can tell, this is an issue with the tutorial-environment and not the tutorial instructions. I'm closing here and recommend anyone who has similar problems follow https://github.com/grafana/tutorial-environment/issues/5

**Closed by matthewhelmke** 2021-06-29 18:59 UTC
Labels: bug

**Comment by zuchka** [comment] 2022-05-19 22:04
the issue is running this setup on a Pi

see https://github.com/grafana/tutorial-environment/issues/5
